import type { ActionItemsLabTask } from "./types";

export const actionItemsLabMockData: ActionItemsLabTask[] = [
  {
    id: "task-01",
    title: "Send revised onboarding checklist to finance and ops",
    owner: "Nina Torres",
    dueDate: "2026-03-28",
    status: "open",
    meetingId: 201,
    meetingTitle: "Operations weekly sync",
    excerpt: "Nina will send the revised onboarding checklist after procurement signs off.",
  },
  {
    id: "task-02",
    title: "Confirm Q2 vendor pricing before Thursday review",
    owner: "Marco Lim",
    dueDate: "2026-03-30",
    status: "open",
    meetingId: 201,
    meetingTitle: "Operations weekly sync",
    excerpt: "Marco is following up with vendors to lock pricing ahead of the Thursday review.",
  },
  {
    id: "task-03",
    title: "Publish the finalized launch FAQ in the customer hub",
    owner: "Jamie Cruz",
    dueDate: "2026-03-31",
    status: "open",
    meetingId: 202,
    meetingTitle: "Launch readiness standup",
    excerpt: "Jamie owns the final FAQ draft and will post it once product signs off.",
  },
  {
    id: "task-04",
    title: "Create follow-up list for inactive beta accounts",
    owner: null,
    dueDate: "2026-04-01",
    status: "open",
    meetingId: 202,
    meetingTitle: "Launch readiness standup",
    excerpt: "The team needs a clean list of inactive beta accounts for outreach.",
  },
  {
    id: "task-05",
    title: "Update the board deck with retention callouts",
    owner: "Nina Torres",
    dueDate: "2026-04-02",
    status: "open",
    meetingId: 203,
    meetingTitle: "Budget alignment review",
    excerpt: "Nina will refresh the board deck and highlight retention movement.",
  },
  {
    id: "task-06",
    title: "Draft customer email for the mobile release delay",
    owner: "Alden Reyes",
    dueDate: "2026-04-03",
    status: "open",
    meetingId: 203,
    meetingTitle: "Budget alignment review",
    excerpt: "Alden will prepare a customer-facing delay note for review.",
  },
  {
    id: "task-07",
    title: "Schedule legal review for the reseller agreement",
    owner: "Priya Santos",
    dueDate: "2026-04-05",
    status: "open",
    meetingId: 204,
    meetingTitle: "Partnerships sync",
    excerpt: "Legal review needs to happen before the new reseller agreement is sent.",
  },
  {
    id: "task-08",
    title: "Prepare examples for the internal AI usage policy",
    owner: null,
    dueDate: null,
    status: "open",
    meetingId: 205,
    meetingTitle: "AI governance workshop",
    excerpt: "The policy needs real examples so teams understand acceptable usage.",
  },
  {
    id: "task-09",
    title: "Share annotated competitor notes with product marketing",
    owner: "Lara Ong",
    dueDate: null,
    status: "open",
    meetingId: 205,
    meetingTitle: "AI governance workshop",
    excerpt: "Lara will package the annotated notes for product marketing.",
  },
  {
    id: "task-10",
    title: "Close open procurement checklist from March planning",
    owner: "Marco Lim",
    dueDate: "2026-03-27",
    status: "complete",
    meetingId: 206,
    meetingTitle: "Sprint retrospective",
    excerpt: "Marco wrapped the remaining procurement checklist items.",
  },
  {
    id: "task-11",
    title: "Post retrospective notes in the team workspace",
    owner: "Jamie Cruz",
    dueDate: "2026-03-29",
    status: "complete",
    meetingId: 206,
    meetingTitle: "Sprint retrospective",
    excerpt: "Jamie posted the retro notes and tagged all action owners.",
  },
  {
    id: "task-12",
    title: "Finalize support escalation matrix for pilot launch",
    owner: "Alden Reyes",
    dueDate: "2026-04-05",
    status: "complete",
    meetingId: 202,
    meetingTitle: "Launch readiness standup",
    excerpt: "The support escalation matrix is ready for the pilot launch.",
  },
];
